// Get Products list 
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
// Delete a Product
export const DELETE_A_PRODCUT_REQUEST = "DELETE_A_PRODCUT_REQUEST"
export const DELETE_A_PRODCUT_SUCCESS = "DELETE_A_PRODCUT_SUCCESS";
export const DELETE_A_PRODCUT_FAIL = "DELETE_A_PRODCUT_FAIL";
// Product Details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// Cart 
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DELETE_CART = "DELETE_CART";
export const SET_CART_TOTAL = "SET_CART_TOTAL";
export const SAVE_SHIPPING_ADRESS = "SAVE_SHIPPING_ADRESS";

// Create New Order 
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const RESET_ORDER = "RESET ORDER";
// get My Order
export const GET_MY_ORDER_REQUEST = "GET_MY_ORDER_REQUEST";
export const GET_MY_ORDER_SUCCESS = "GET_MY_ORDER_SUCCESS";
export const GET_MY_ORDER_FAIL = "GET_MY_ORDER_FAIL";
// Delete Order
export const DELETE_A_ORDER_REQUEST="DELETE_A_ORDER_REQUEST"
export const DELETE_A_ORDER_SUCCESS = "DELETE_A_ORDER_SUCCESS";
export const DELETE_A_ORDER_FAIL = "DELETE_A_ORDER_FAIL";
// get My Order
export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAIL = "GET_ALL_ORDER_FAIL";
// Update Order Status
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST"
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";